# Generated by Django 2.2.6 on 2020-01-26 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bagian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('acara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Acara')),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tgl_dibuat', models.DateTimeField()),
                ('batas_tgl', models.DateTimeField()),
                ('status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('komentar', models.TextField(blank=True, null=True)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='attachment_file/')),
                ('bagian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Bagian')),
                ('tugas_untuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
