# Generated by Django 2.1.5 on 2020-07-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20200717_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagian',
            old_name='Divisi',
            new_name='divisi',
        ),
    ]
